db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:auth-server}
  user: ${DB_USER:auth-server}
  pass: ${DB_PASSWORD:auth-server}

spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
  jpa:
    hibernate:
      ddl-auto: create
