spring:
  datasource:
    url: jdbc:postgresql://${db.server.host}:${db.server.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
    data: classpath:db/test-data.sql
  jpa:
    hibernate:
      ddl-auto: create
